apiVersion: v1
kind: Service
metadata:
  labels:
    name: rusticana-frontend
  name: rusticana-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 28015
      targetPort: 28015
      protocol: UDP
  selector:
    name: rusticana-server
